# Generated by Django 3.1.6 on 2021-02-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestorage',
            name='game_webpage_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='streamstorage',
            name='vod_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='streamstorage',
            name='vod_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamestorage',
            name='game_slug',
            field=models.SlugField(max_length=200),
        ),
    ]
